# Generated by Django 3.1.6 on 2021-02-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='exploration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
