# Generated by Django 3.1.6 on 2021-02-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20210211_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.land'),
        ),
        migrations.AddField(
            model_name='region',
            name='land_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='gold_reward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='recovery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
                ('daytime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='daytime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='daytime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime'),
        ),
        migrations.AddField(
            model_name='training',
            name='daytime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime'),
        ),
    ]
