# Generated by Django 3.1.6 on 2021-02-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20210211_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
        migrations.AddField(
            model_name='training',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
    ]
