# Generated by Django 3.1.6 on 2021-02-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20210211_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='crafting',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='daytime',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gathering',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reputation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['name']},
        ),
    ]
