# Generated by Django 3.1.6 on 2021-02-12 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20210212_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weapon_type',
            field=models.ForeignKey(blank=True, help_text='If equipment_slot is weapon', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.weapon'),
        ),
        migrations.DeleteModel(
            name='RecipeType',
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment_slot',
            field=models.ForeignKey(blank=True, help_text='If not a building', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.equipmentslot'),
        ),
    ]
