# Generated by Django 3.1.6 on 2021-02-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20210212_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['gathering', 'adventure', 'crafting', 'land', 'weapon']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
