# Generated by Django 3.1.6 on 2021-02-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20210212_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
