# Generated by Django 3.1.6 on 2021-02-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_npc_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='weapon_type',
            new_name='weapon',
        ),
    ]
