# Generated by Django 3.1.6 on 2021-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_auto_20210215_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='comfort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
