# Generated by Django 3.1.6 on 2021-02-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_guild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
                ('level', models.IntegerField(default=1)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('reputation_guild_value', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('daytime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.guild')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc')),
                ('reputation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.reputation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
