# Generated by Django 3.1.6 on 2021-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='quest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
