# Generated by Django 3.1.7 on 2021-02-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_auto_20210221_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.guild'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.guild'),
        ),
    ]
