# Generated by Django 3.1.7 on 2021-02-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0024_auto_20210224_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='daytime',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='daytime',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='daytime',
        ),
    ]
