# Generated by Django 3.1.7 on 2021-03-01 18:34

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0025_auto_20210224_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='geom',
            field=djgeojson.fields.PolygonField(blank=True, null=True),
        ),
    ]
