# Generated by Django 3.2.2 on 2021-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0026_region_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reputation_guild_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
