# Generated by Django 3.2.2 on 2021-05-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0027_alter_book_reputation_guild_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_fr',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_fr',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='image',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='image_fr',
        ),
    ]
