# Generated by Django 3.2.2 on 2021-05-11 15:35

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('front', '0028_auto_20210510_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='style',
        ),
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_icon', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
