# Generated by Django 3.2.2 on 2021-05-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0030_material_materialtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='type',
            new_name='material_type',
        ),
    ]
