# Generated by Django 3.2.2 on 2021-05-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0033_alter_material_durability'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
                ('level', models.IntegerField()),
                ('lithram', models.IntegerField()),
                ('magnam', models.IntegerField()),
                ('radiam', models.IntegerField()),
                ('hydram', models.IntegerField()),
                ('pyram', models.IntegerField()),
                ('stratam', models.IntegerField()),
                ('encumbrance', models.IntegerField()),
                ('ingredient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.ingredienttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
