# Generated by Django 3.2.2 on 2021-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0036_alter_ingredient_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True)),
                ('level', models.IntegerField()),
                ('activator', models.IntegerField(blank=True, null=True)),
                ('binder', models.IntegerField(blank=True, null=True)),
                ('energizer', models.IntegerField(blank=True, null=True)),
                ('deteriorator', models.IntegerField(blank=True, null=True)),
                ('focuser', models.IntegerField(blank=True, null=True)),
                ('fortifier', models.IntegerField(blank=True, null=True)),
                ('putrefier', models.IntegerField(blank=True, null=True)),
                ('stimulator', models.IntegerField(blank=True, null=True)),
                ('tranquilizer', models.IntegerField(blank=True, null=True)),
                ('toner', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField()),
                ('encumbrance', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
