# Generated by Django 3.2.7 on 2021-09-20 14:40

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0040_blueflagsreward_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueflags',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
