# Generated by Django 3.2.7 on 2021-09-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0041_alter_blueflags_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueflagsstep',
            old_name='adventure_value',
            new_name='difficulty',
        ),
    ]
