# Generated by Django 3.2.7 on 2021-10-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0042_rename_adventure_value_blueflagsstep_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueflagsreward',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.ingredient'),
        ),
        migrations.AddField(
            model_name='blueflagsreward',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.plant'),
        ),
    ]
