# Generated by Django 3.2.7 on 2021-10-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0044_material_lightness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='daytime',
        ),
        migrations.RemoveField(
            model_name='training',
            name='gold_reward',
        ),
        migrations.RemoveField(
            model_name='training',
            name='recovery',
        ),
    ]
