# Generated by Django 3.2.7 on 2021-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0045_auto_20211007_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='elioam',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='frimam',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='lectram',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='psycham',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
