# Generated by Django 3.2.7 on 2021-10-13 07:46

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0046_auto_20211007_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elixir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
            ],
        ),
    ]
