# Generated by Django 3.2.7 on 2021-10-13 08:26

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('front', '0049_alter_gatheringpoint_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatheringpoint',
            name='icon',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_icon', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_icon', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_icon', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
