# Generated by Django 3.2.7 on 2021-10-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0051_book_blueflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueflagsstep',
            name='gathering',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.gathering'),
        ),
        migrations.AddField(
            model_name='blueflagsstep',
            name='weapon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.weapon'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='blueflag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.adventure'),
        ),
    ]
