# Generated by Django 3.2.7 on 2021-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0053_auto_20211024_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('contact', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
