# Generated by Django 3.2.7 on 2021-10-25 20:29

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('front', '0054_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueflags',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueflag_icon', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
