# Generated by Django 3.2.7 on 2021-10-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0055_blueflags_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='difficulty',
            new_name='craft_difficulty',
        ),
    ]
