# Generated by Django 3.2.7 on 2021-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0056_rename_difficulty_material_craft_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cooldown',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='harvest_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='craft_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
