# Generated by Django 3.2.7 on 2021-10-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0057_auto_20211026_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='difficulty',
            new_name='craft_difficulty',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='encumbrance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='encumbrance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
