# Generated by Django 3.2.7 on 2021-10-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0058_auto_20211026_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='difficulty',
            new_name='craft_difficulty',
        ),
    ]
