# Generated by Django 3.2.7 on 2021-10-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0060_auto_20211026_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cooldown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cooldown',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
