# Generated by Django 3.2.7 on 2021-10-30 07:08

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0063_auto_20211028_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Somberseason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
            ],
        ),
    ]
