# Generated by Django 3.2.7 on 2021-10-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0064_somberseason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spell',
            new_name='Talent',
        ),
    ]
