# Generated by Django 3.2.7 on 2021-10-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0066_rename_ingredient_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueflagsreward',
            old_name='ingredient',
            new_name='component',
        ),
    ]
