# Generated by Django 3.2.7 on 2021-10-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0067_rename_ingredient_blueflagsreward_component'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientType',
            new_name='ComponentType',
        ),
    ]
