# Generated by Django 3.2.7 on 2021-10-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0068_rename_ingredienttype_componenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='ingredient_type',
            new_name='component_type',
        ),
    ]
