# Generated by Django 3.2.7 on 2021-11-01 15:12

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0070_boss_bossweakness_magicschool_monster_monsterweakness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='magicschool',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='boss',
            name='location',
        ),
        migrations.AddField(
            model_name='boss',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
