# Generated by Django 3.2.7 on 2021-11-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0071_auto_20211101_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossweakness',
            name='bonus',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], default='+', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='monsterweakness',
            name='bonus',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], default='+', max_length=1, null=True),
        ),
    ]
