# Generated by Django 3.2.7 on 2021-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0072_auto_20211102_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='cooldown',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default='Daily', max_length=16, null=True),
        ),
    ]
