# Generated by Django 3.2.7 on 2021-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0074_auto_20211115_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='elite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monster',
            name='elite',
            field=models.BooleanField(default=False),
        ),
    ]
