# Generated by Django 3.2.7 on 2021-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0075_auto_20211115_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='craft_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='craft_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='craft_difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
