# Generated by Django 3.2.7 on 2022-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0078_rename_harvest_materialtype_gathering'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueflagsreward',
            name='notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
