# Generated by Django 3.2.7 on 2022-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0079_blueflagsreward_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueflagsreward',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
