# Generated by Django 3.2.7 on 2022-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0080_alter_blueflagsreward_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueflagsreward',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
