# Generated by Django 3.2.7 on 2022-08-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0083_auto_20220814_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueflagsstep',
            name='monster1_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueflagsstep',
            name='monster2_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueflagsstep',
            name='monster3_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueflagsstep',
            name='monster4_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueflagsstep',
            name='monster5_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
