# Generated by Django 3.2.7 on 2022-08-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0084_auto_20220814_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueflagsstep',
            name='is_fight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
